36: Dark mode support toggle
ofir-zeitoun/expenses-client pull request #38
Opened 2024-04-30 16:22 UTC by shakedlv

2024-05-02 12:06 UTC, shakedlv reviewed
To - Do :
1) Add all colors  from figma with a proper naming convention.
2) Move theme switcher toggle to a better position

2024-05-05 13:17 UTC, ofir-zeitoun requested changes
minor fixes

2024-05-05 13:17 UTC, ofir-zeitoun commented on src/components/theme-switcher/theme-switcher.css
> +@import '../../index.css';
try move import index.css to main

2024-05-05 13:17 UTC, ofir-zeitoun commented on src/components/theme-switcher/theme-switcher.css
> +.btn-color-mode-switch > label.btn-color-mode-switch-inner{
you can nest it in lines 14-18

2024-05-05 13:17 UTC, ofir-zeitoun commented on src/components/theme-switcher/theme-switcher.css
> +    margin: 0px;
change px to rem

2024-05-05 13:20 UTC, ofir-zeitoun commented on src/components/theme-switcher/theme-switcher.tsx
> +  const isSystemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
use useThemeMode hook

2024-05-06 15:26 UTC, shakedlv reviewed
Fixed Comments
- Moved css imports to main
- nested css 
- formated css , change to rem
- export theme logic to useTheme hook

2024-05-07 15:27 UTC, ofir-zeitoun commented on src/components/theme-switcher/theme-switcher.css
> +@import '../../index.css';
Couldn't move?

2024-05-26 13:34 UTC, ofir-zeitoun commented on src/components/nav-bar/nav-bar.tsx
> +import { ThemeSwitcher } from "../theme-switcher";
move up

2024-05-26 13:36 UTC, ofir-zeitoun approved these changes

2024-05-26 13:40 UTC, merged